#!/usr/bin/env python

import os
import sys

os.path.join(os.environ["HOME"], "emotion")

sys.argv[0]="Emotion"

if len(sys.argv) == 1:
    # no args ? -> I add "-?"
    sys.argv.append("-?")

execfile(os.path.join(os.environ["HOME"], "server/src", "Emotion.py"))

