#!/usr/bin/env python

import os
import sys

EMOTION_PATH = os.path.join(os.environ["HOME"], "emotion")

sys.path.insert(0, EMOTION_PATH)
sys.path.insert(0, os.path.join(EMOTION_PATH, "tango"))

sys.argv[0]="Emotion"
execfile(os.path.join(EMOTION_PATH, "tango", "Emotion.py"))

