#!/usr/bin/env python

import os
import sys
sys.path.insert(0, "/users/blissadm/emotion")
sys.path.insert(0, "/users/blissadm/emotion/tango")

#os.environ["TANGO_HOST"]="lpellab:20000"

sys.argv[0]="Emotion"
execfile("/users/blissadm/emotion/tango/Emotion.py")

